addons:
  rethinkdb: '2.3.6'

before_install:
  - npm run --prefix ./api install
  - npm run --prefix ./client install

language: node_js

node_js:
  - 'node'

script:
  - npm run lint
  - npm run test
